import PDFDocument from "pdfkit";

const renderSimpleBar = (value, max = 100) => {
  const safe = Math.max(0, Math.min(max, Number(value) || 0));
  const blocks = Math.round((safe / max) * 20);
  return `${"█".repeat(blocks)}${"░".repeat(20 - blocks)} ${safe}`;
};

export const generateReportPdfBuffer = async (report, metrics = null) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc
      .fontSize(20)
      .text("Smart Disaster & Relief Management Report", { align: "center" })
      .moveDown(1.2);

    doc.fontSize(12).text(`Title: ${report.title}`);
    doc.text(`Report Type: ${report.report_type}`);
    doc.text(`Created At: ${new Date(report.created_at).toLocaleString()}`);
    doc.text(`Disaster ID: ${report.disaster_id || "N/A"}`);
    doc.text(`Generated By: ${report.generated_by || "N/A"}`);
    doc.moveDown(1);

    doc.fontSize(13).text("Report Content", { underline: true }).moveDown(0.5);
    doc.fontSize(11).text(report.content || "No additional details.");

    if (metrics) {
      doc.moveDown(1.2);
      doc.fontSize(13).text("Operational Metrics Snapshot", { underline: true }).moveDown(0.5);
      doc.fontSize(11).text(`Total Disasters: ${metrics.totalDisasters}`);
      doc.text(`Active Disasters: ${metrics.activeDisasters}`);
      doc.text(`Critical Disasters: ${metrics.criticalDisasters}`);
      doc.text(`Total Resource Quantity: ${metrics.totalResourceQuantity}`);
      doc.text(`Low Stock Rate: ${metrics.lowStockRate}%`);
      doc.moveDown(0.8);
      doc.text("Critical Load");
      doc.text(renderSimpleBar(metrics.criticalDisasterRate));
      doc.text("Resource Health");
      doc.text(renderSimpleBar(100 - metrics.lowStockRate));
    }

    doc.end();
  });
};
